server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dagrix
    username: dagrix
    password: cyIgsFHpJ9JQXAHSCEo0vhylorZVejLC

#    url: jdbc:postgresql://dpg-cg4kvcseoogtrlt2cv00-a.oregon-postgres.render.com:5432/dagrix
#    username: dagrix
#    password: 123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update    # har safar restart bo'lganda update bo'ladi
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


upload:
  server:
    folder: C:/rasmlar

jwt:
  token:
    secret: hellojwttoken        # secret key
    validity: 86400000           # yashash muddati. millisekundlarda beriladi
