server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dagrix
    username: dagrix
    password: 123

#    url: jdbc:postgresql://localhost:5432/test
#    username: test_user
#    password: Test123.Test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update    # har safar restart bo'lganda update bo'ladi
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


upload:
  server:
    folder: C:/rasmlar

jwt:
  token:
    secret: hellojwttoken        # secret key
    validity: 86400000           # yashash muddati. millisekundlarda beriladi
